language: node_js
node_js:
  - "0.10"
env: TAP_TIMEOUT=120
before_install:
  - sudo add-apt-repository -y ppa:lyrasis/precise-tools
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
