language: node_js
node_js:
  - "0.10"
env: TAP_TIMEOUT=120
before_install:
  - wget http://www.imagemagick.org/download/ImageMagick.tar.bz2
  - tar xf ImageMagick.tar.bz2
  - cd ImageMagick*
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
