language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
 - wget https://launchpad.net/ubuntu/+archive/primary/+files/libmagick%2B%2B-6.q16-5_6.8.9.9-5_amd64.deb
 - sudo dpkg -i libmagick++-6.q16-5_6.8.9.9-5_amd64.deb
