language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - wget http://www.imagemagick.org/download/releases/ImageMagick-6.8.7-10.tar.bz2
  - tar xf ImageMagick-6.8.7-10.tar.bz2
  - cd ImageMagick*
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
